UPDATE dbo.DataSet SET Stub = 'Usage' WHERE Id = 1
UPDATE dbo.DataSet SET Stub = 'Crimes' WHERE Id = 2
UPDATE dbo.DataSet SET Stub = 'PrisonPopulation' WHERE Id = 3
UPDATE dbo.DataSet SET Stub = 'Worried' WHERE Id = 4
UPDATE dbo.DataSet SET Stub = 'Traffic' WHERE Id = 5
UPDATE dbo.DataSet SET Stub = 'Collisions' WHERE Id = 6
UPDATE dbo.DataSet SET Stub = 'Injuries' WHERE Id = 7
UPDATE dbo.DataSet SET Stub = 'Classifications' WHERE Id = 8
UPDATE dbo.DataSet SET Stub = 'LocalPrices' WHERE Id = 9
UPDATE dbo.DataSet SET Stub = 'OpenPrices' WHERE Id = 10
UPDATE dbo.DataSet SET Stub = 'Bedrooms' WHERE Id = 11
UPDATE dbo.DataSet SET Stub = 'Types' WHERE Id = 12
UPDATE dbo.DataSet SET Stub = 'Units' WHERE Id = 13
UPDATE dbo.DataSet SET Stub = 'Arrivals' WHERE Id = 14
UPDATE dbo.DataSet SET Stub = 'Departures' WHERE Id = 15
UPDATE dbo.DataSet SET Stub = 'Harbour' WHERE Id = 16
UPDATE dbo.DataSet SET Stub = 'CondorPunctuality' WHERE Id = 17
UPDATE dbo.DataSet SET Stub = 'Cruises' WHERE Id = 18
UPDATE dbo.DataSet SET Stub = 'Post16results' WHERE Id = 19
UPDATE dbo.DataSet SET Stub = 'GcseOverall' WHERE Id = 20
UPDATE dbo.DataSet SET Stub = 'GcseSchool' WHERE Id = 21
UPDATE dbo.DataSet SET Stub = 'StudentsInUk' WHERE Id = 22
UPDATE dbo.DataSet SET Stub = 'Population' WHERE Id = 23
UPDATE dbo.DataSet SET Stub = 'Age' WHERE Id = 24
UPDATE dbo.DataSet SET Stub = 'AgeMale' WHERE Id = 25
UPDATE dbo.DataSet SET Stub = 'AgeFemale' WHERE Id = 26
UPDATE dbo.DataSet SET Stub = 'Birthplace' WHERE Id = 27
UPDATE dbo.DataSet SET Stub = 'Changes' WHERE Id = 28
UPDATE dbo.DataSet SET Stub = 'District' WHERE Id = 29
UPDATE dbo.DataSet SET Stub = 'Parish' WHERE Id = 30
UPDATE dbo.DataSet SET Stub = 'EarningsAgeGroup' WHERE Id = 31
UPDATE dbo.DataSet SET Stub = 'EarningsSector' WHERE Id = 32
UPDATE dbo.DataSet SET Stub = 'EarningsSex' WHERE Id = 33
UPDATE dbo.DataSet SET Stub = 'Changes' WHERE Id = 34
UPDATE dbo.DataSet SET Stub = 'RpiGroupChanges' WHERE Id = 35
UPDATE dbo.DataSet SET Stub = 'RpixGroupChanges' WHERE Id = 36
UPDATE dbo.DataSet SET Stub = 'DomesticConsumption' WHERE Id = 37
UPDATE dbo.DataSet SET Stub = 'Types' WHERE Id = 38
UPDATE dbo.DataSet SET Stub = 'Totals' WHERE Id = 39
UPDATE dbo.DataSet SET Stub = 'Sectors' WHERE Id = 40
UPDATE dbo.DataSet SET Stub = 'Annual' WHERE Id = 41
UPDATE dbo.DataSet SET Stub = 'Monthly' WHERE Id = 42
UPDATE dbo.DataSet SET Stub = 'FrostDays' WHERE Id = 43
UPDATE dbo.DataSet SET Stub = 'Banking' WHERE Id = 44
UPDATE dbo.DataSet SET Stub = 'FundsUnderManagement' WHERE Id = 45
UPDATE dbo.DataSet SET Stub = 'Concerns' WHERE Id = 46
UPDATE dbo.DataSet SET Stub = 'Totals' WHERE Id = 47
UPDATE dbo.DataSet SET Stub = 'MedUnitBedDaysFiveYrAvg' WHERE Id = 48
UPDATE dbo.DataSet SET Stub = 'Attendances' WHERE Id = 49
UPDATE dbo.DataSet SET Stub = 'Contributions' WHERE Id = 50
UPDATE dbo.DataSet SET Stub = 'Cruises' WHERE Id = 51
UPDATE dbo.DataSet SET Stub = 'AirByMonth' WHERE Id = 52
UPDATE dbo.DataSet SET Stub = 'SeaByMonth' WHERE Id = 53
UPDATE dbo.DataSet SET Stub = 'ElectricityConsumption' WHERE Id = 54
UPDATE dbo.DataSet SET Stub = 'ElectricityImportVsGenerated' WHERE Id = 55
UPDATE dbo.DataSet SET Stub = 'RegisteredVehicles' WHERE Id = 56
UPDATE dbo.DataSet SET Stub = 'Breakdown' WHERE Id = 57
UPDATE dbo.DataSet SET Stub = 'Source' WHERE Id = 58
UPDATE dbo.DataSet SET Stub = 'Gas' WHERE Id = 59
UPDATE dbo.DataSet SET Stub = 'Oil' WHERE Id = 60
UPDATE dbo.DataSet SET Stub = 'Renewable' WHERE Id = 61
UPDATE dbo.DataSet SET Stub = 'CommercialAndIndustrial' WHERE Id = 62
UPDATE dbo.DataSet SET Stub = 'ConstructionAndDemolition' WHERE Id = 63
UPDATE dbo.DataSet SET Stub = 'Household' WHERE Id = 64
UPDATE dbo.DataSet SET Stub = 'NitrateConcentration' WHERE Id = 65
UPDATE dbo.DataSet SET Stub = 'PollutionIncidents' WHERE Id = 66
UPDATE dbo.DataSet SET Stub = 'UnaccountedWater' WHERE Id = 67
UPDATE dbo.DataSet SET Stub = 'WaterConsumption' WHERE Id = 68
UPDATE dbo.DataSet SET Stub = 'WaterQualityCompliance' WHERE Id = 69
UPDATE dbo.DataSet SET Stub = 'WaterStorage' WHERE Id = 70

UPDATE dbo.DataCategory SET Stub = 'OverseasAid' WHERE Stub = 'overseas_aid'